on:
  push:
    branches:
      - main

jobs:
  print_context:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT > env.txt
      - name: Rebase
        run: |
          python rebaser.py
          git config --local user.name "GITHUB BUILD"
          git config user.email github-actions@github.com
          git add -f commit_history.txt
          git commit -m ${GITHUB_SHA}
      - name: Push the commit_history.txt
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
      - name: Filter
        run: |
          git filter-branch --tree-filter 'rm -f test.bin' HEAD
          git gc --prune=now
